services:
  redis:
    restart:
      always
    container_name: redis
    hostname: redis
    image: redis/redis-stack-server:latest
    environment:
      REDIS_ARGS: --appendonly yes --appendfsync always --rdbcompression yes
    ports:
      - 6666:6379

  redis-commander:
    restart:
      always
    container_name: redis-commander
    hostname: redis-commander
    image: rediscommander/redis-commander:latest
    build: .
    environment:
      - REDIS_HOSTS=local:redis:6379
    ports:
      - 8089:8081

  broker:
    restart:
      always
    image: broker
    build:
      context: .
      dockerfile: ./cmd/redis-broker/Dockerfile
    command: start
    ports:
      - 8083:8080
    environment:
      BROKER_CONFIG_PATH: /broker-config/config.yaml
      REDIS_ADDRESS: redis:6379 
    volumes:
      - ./example-config.yaml:/broker-config/config.yaml

  sockeye:
    restart:
      always
    image: docker.io/n3wscott/sockeye:v0.7.0@sha256:e603d8494eeacce966e57f8f508e4c4f6bebc71d095e3f5a0a1abaf42c5f0e48
    ports:
      - 8082:8080